name: Dockerized Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/shop-backend:latest
      
      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./client
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/shop-frontend:latest



  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            echo "🚀 Connecting to server..."

            # Clone repo if not exists
            if [ ! -d "/home/ubuntu/E-Commerce" ]; then
              git clone https://github.com/BhavishyaSahay/E-Commerce.git /home/ubuntu/E-Commerce
            fi

            cd /home/ubuntu/E-Commerce

            echo "Pull latest code"
            git pull origin main

            echo "Pull latest Docker images"
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/shop-backend:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/shop-frontend:latest

            echo "Stop old containers"
            docker compose down

            echo "Clean old images (optional)"
            docker system prune -f

            echo "Start new containers"
            docker compose up -d

            echo "Deployment completed"
        

